name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret Test_1 will be masked:  "
          echo ${{ secrets.Test_1 }}
          echo "Trick to echo GitHub Actions Secret Test_1:  "
          echo ${{secrets.Test_1}}
          echo "The GitHub Action Secret Test_2 will be masked:  "
          echo ${{ secrets.Test_2 }}
          echo "Trick to echo GitHub Actions Secret Test_2:  "
          echo ${{secrets.Test_2}} | sed 's/./& /g' 
          
